### ISSUE TITLE
How do we define a paragraph?

### ISSUE THREAD

**Issue by norakassner** [bigscience-workshop/metadata#114]
https://docs.google.com/document/d/1S2gQrOZl5UVwILboc9E4wwmXJtO2QmfNq4B_pTdzYS0

**Comment by tianjianjiang** [comment]
Since @timoschick has noted https://docs.google.com/document/d/1S2gQrOZl5UVwILboc9E4wwmXJtO2QmfNq4B_pTdzYS0, I suppose we can close this ticket.
