### ISSUE TITLE
feat: add an option for loss calculation for local metadata

### ISSUE THREAD

**Issue by SaulLu** [bigscience-workshop/metadata#34]
# Add an option for loss calculation for local metadata

## Feature description

Currently tokens corresponding to local metadata are not taken into account in the loss calculation. We would like to add an option in the training arguments to choose to take them into account or not.

**Comment by tianjianjiang** [comment]
> tokens corresponding to local metadata are not taken into account in the loss calculation

May I ask for an example and its counterexample for this? Not sure I fully understand it... sorry.

**Comment by tianjianjiang** [comment]
Seems done by #39.
