### ISSUE TITLE
Rename dateutil submodule with another name

### ISSUE THREAD

**Issue by cccntu** [bigscience-workshop/metadata#63]
There are reports that the current approach might not work with `pip install`.
So I am planning to drop the submodule, and rename the modified dateutil so we can add it to requirements.

cc. @SaulLu @shanyas10

**Comment by SaulLu** [comment]
Great! Thank you very much @cccntu, indeed as discussed offline I think this is the best approach to take too!

**Comment by SaulLu** [comment]
Let me also ping you @chkla on this issue because it seems to me that you also uses the `dateutil` package in your scripts :slightly_smiling_face:
