### ISSUE TITLE
Conflict in torch version

### ISSUE THREAD

**Issue by manandey** [bigscience-workshop/metadata#66]
The torch version used in the requirements.txt is 1.8.1 which seems to have some issue with the flair library I am using (flairNLP/flair#2137). Can we use torch==1.9.0 instead? @SaulLu @cccntu

**Comment by SaulLu** [comment]
I think we can test and see if it blocks elsewhere (on JZ there seems to be the 1.9.0 version available)

**Comment by cccntu** [comment]
I don't mind upgrading. Feel free to open a PR and hopefully we have small tests covering that.

Personally I usually leave torch outside of requirements.txt and install it manually or in a makefile.
