### ISSUE TITLE
Improve: Entity extraction speed

### ISSUE THREAD

**Issue by SaulLu** [bigscience-workshop/metadata#78]
If I understand correctly, the extraction strategic for entity metadata uses the [REL library](https://github.com/informagi/REL). REL uses a flair model to do entity detection. I think it's quite possible that this kind of model could take advantage of batching : that would be very interesting for our dataset processing! 

Currently, with a speed of 5000 examples every 50min. Even if we didn't choose yet the final size of the dataset, it would take 2536 days to process all c4/en.

**Comment by tianjianjiang** [comment]
duplicated: #95
